modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "anticreate"
version = "0.0.3b"
displayName = "AntiCreate"
authors = "ElAntCar"
description = '''Adds a Brass Rocket (Insta Power 4)'''

[[dependencies.anticreate]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.anticreate]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.anticreate]]
    modId = "create"
    type = "required"
    versionRange = "[6.0,)"
    ordering = "AFTER"
    side = "BOTH"
