modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "brassrocket"
version = "0.0.1b"
displayName = "Brass Rocket"
authors = "ElAntCar"
description = '''Brass Rocket (Insta Power 3)'''

[[dependencies.brassrocket]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.brassrocket]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.brassrocket]]
    modId = "create"
    type = "required"
    versionRange = "[6.0,)"
    ordering = "AFTER"
    side = "BOTH"
